### ISSUE TITLE
xapax.gitbooks.io - site can't be reached

### ISSUE THREAD

**Issue by d1th** [xapax/security#1]
I don't know if it's temporary but I'm unable to access the link provided. It seems https://gitbookio.gitbooks.io/documentation/ still functions as does gitbooks.io.

**Comment by xapax** [comment]
It seems to be working again now. Gitbook seems to be migrating to a new version. I still can't edit the book through the new version of gitbook, only in legacy mode. And they haven't provided a migration-functionality for books that does not belong to an organization yet.
Thanks for addressing the issue!
